import ma3Light from "./ControlAssets/ma3Light.png";
import ma3CompactXT from "./ControlAssets/ma3CompactXT.png";
import ma2Light from "./ControlAssets/ma2Light.png";

const fixtures = [
  {
    name: "grandMA3 light",
    nameID: "ma3Light",
    image: ma3Light,
    desc: "",
    info: "The grandMA3 compact XT console is the larger of the two compact models, offering the full system benefits of the grandMA3 system, housed in a compact and lightweight format. Easy to transport, the compact models are ideal for owner/operators and also the console of choice for tech-desk duties.",
    specs: [
      " Real-time control for up to 250 000 parameters per session in connection with grandMA3 processing units",
      "2 internal foldable monitor multi-touch screens",
      "2 internal letterbox multi-touch screens",
      "2 internal multi-touch command screens",
      "2 external multi-touch screens can be connected",
      "41 rotary RGB backlit encoder",
      "5 backlit dual encoders",
      "15 backlit motorized 60 mm faders",
      "60 separate playbacks",
      "16 assignable x-keys",
      "Integrated keyboard drawer",
      "Built-in uninterruptible power supply (UPS)",
      "3 etherCON connectors, 6 USB connectors",
      "2 backlit motorized A/B faders 100 mm",
      "Individually backlit and dimmable silent (clickless) keys",
    ],
    vid: "https://www.youtube.com/embed/1-FQVsgmDcY",
    url: "/control/ma3Light",
  },
  {
    name: "grandMA3 Compact XT",
    nameID: "ma3CompactXT",
    image: ma3CompactXT,
    desc: "",
    info: "ma3CompactXT ATMe Haze Generator was designed with safety and reliability in mind and is capable of generating pure white, non-toxic haze for as long as you have fluid (100% duty cycle). This generator is also equipped, as a standard feature, with the Automatic Purging System (APS). This system purges the heating module after the first heating cycle and after every emission of haze preventing residual build up and clogging. Requires a CO2 tank to run.",
    specs: [
      " Real-time control for up to 250 000 parameters per session in connection with grandMA3 processing units",
      "6 DMX outputs, 1 DMX input",
      "2 internal foldable monitor multi-touch screens",
      "1 external multi-touch screen can be connected",
      "39 rotary RGB backlit encoder",
      "5 dual encoders",
      "41 rotary RGB backlit encoder",
      "5 dual encoders",
      "15 backlit motorized 60 mm faders",
      "60 separate playbacks",
      "16 assignable x-keys",
      "3 etherCON connectors, 6 USB connectors",
      "2 backlit motorized A/B faders 100 mm",
      "Individually backlit and dimmable silent (clickless) keys",
    ],
    vid: "https://www.youtube.com/embed/2bgCrCeFrLM",
    url: "/control/ma3CompactXT",
  },
  {
    name: "grandMA2 Light",
    nameID: "ma2Light",
    image: ma2Light,
    desc: "",
    info: "ma2Light ATMe Haze Generator was designed with safety and reliability in mind and is capable of generating pure white, non-toxic haze for as long as you have fluid (100% duty cycle). This generator is also equipped, as a standard feature, with the Automatic Purging System (APS). This system purges the heating module after the first heating cycle and after every emission of haze preventing residual build up and clogging. Requires a CO2 tank to run.",
    specs: [
      "Real-time control for up to 65,536 parameters per session in connection with MA NPU (equivalent to 256 DMX universes)",
      "4,096 HTP/LTP parameters",
      "6 DMX outputs",
      '2 internal TFT wide mode touchscreens (15.4" WXGA)',
      "2 external TFT screens can be connected (UXGA, touchscreens accepted)",
      '1 internal command screen – multi-touch (9" SVGA)',
      "15 motorized executor faders",
      "Integrated keyboard drawer",
      "Built-in uninterruptible power supply (UPS)",
      "2 etherCON connectors, 5 USB 2.0 connectors",
      "Motorized monitor wing",
      "2 motorized A/B fader (100mm)",
      "Individually backlit and dimmable silent (clickless) keys",
    ],
    vid: "https://www.youtube.com/embed/LB5xcLT0VMg",
    url: "/control/ma2Light",
  },
];

export default fixtures;
