// import "./GalleryAssets/ConcertAssets";

const Images = [
  {
    img: require("./GalleryAssets/ConcertAssets/concert-1.png").default,
    id: 1,
    type: "concert",
    text: "Watershed",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-2.png").default,
    id: 2,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-3.png").default,
    id: 3,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-4.png").default,
    id: 4,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-5.png").default,
    id: 5,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-6.png").default,
    id: 6,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-7.png").default,
    id: 7,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-8.png").default,
    id: 8,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-9.png").default,
    id: 9,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-10.png").default,
    id: 10,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-11.png").default,
    id: 11,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-12.png").default,
    id: 12,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-13.png").default,
    id: 13,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-14.png").default,
    id: 14,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-15.png").default,
    id: 15,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-16.png").default,
    id: 16,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-17.png").default,
    id: 17,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-18.png").default,
    id: 18,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-19.png").default,
    id: 19,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-20.png").default,
    id: 20,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-21.png").default,
    id: 21,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-22.png").default,
    id: 22,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-23.png").default,
    id: 23,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-24.png").default,
    id: 24,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-25.png").default,
    id: 25,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-26.png").default,
    id: 26,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-27.png").default,
    id: 27,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-28.png").default,
    id: 28,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-29.png").default,
    id: 29,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-30.png").default,
    id: 30,
    type: "concert",
    text: "",
  },
  {
    img: require("./GalleryAssets/ConcertAssets/concert-31.png").default,
    id: 31,
    type: "concert",
    text: "",
  },
];

export default Images;
